export { default as Header } from '@/components/Header'
export { default as Footer } from '@/components/Footer'
export { default as ProblemRouter } from '@/components/ProblemRouter'
export { default as Timeline } from '@/components/Timeline'
export { default as Informations } from '@/components/Informations'
export { default as Organisators } from '@/components/Organisators'
export { default as Separator } from '@/components/Separator'
export { default as Partners } from '@/components/Partners'
export { default as Background } from '@/components/Background'

export { default as Separator_1 } from '@/assets/Separator_1.svg'
export { default as Separator_2 } from '@/assets/Separator_2.svg'
export { default as Separator_3 } from '@/assets/Separator_3.svg'

export { default as Trees } from '@/assets/Trees.png'
export { default as Mistletoe } from '@/assets/Mistletoe.png'
export { default as Snowman } from '@/assets/Snowman.png'
export { default as Presents } from '@/assets/Presents.png'
export { default as Sarme } from '@/assets/sarme.jpg'

export { default as FerLogo } from '@/assets/FerLogo.png'
export { default as XFERLogo } from '@/assets/XFERLogo.png'
export { default as eestecLogo } from '@/assets/eestecLogo.png'
export { default as Title } from '@/components/Title'
